---
#who is the agent - name
- hosts: web

#we need details about the server
  gather_facts: yes

#we need sudo access
  become: true

#task to replace file
  tasks:
  - name: delete file
    file:
      path: /etc/nginx/sites-available/default
      state: absent
  - name: replace file
    become: true
    copy:
      src: default
      dest: /etc/nginx/sites-available

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes

