---
- hosts: web
  gather_facts: yes
  become: true

  tasks:
  - name: Install Node
    apt: pkg=nodejs state=present update_cache=yes
  - name: Install NPM
    apt: pkg=npm state=present update_cache=yes

