---
- hosts: web
  gather_facts: yes
  become: true
  
  # Adding environment variable to app
  # Run Node App
  tasks:
  - name: Starting the app
    shell: |
      cd app/app/
      npm i
      node seeds/seed.js
      npm start
    environment:
      DB_HOST: mongodb://192.168.33.11:27017/posts
