---
#who is the agent - name
- hosts: all

#we need details about the server
  gather_facts: yes

#we need sudo access
  become: true

#task to replace file
  tasks:
  - name: copy app over
    become: true
    copy:
      src: app
      dest: .
  
  